### ISSUE TITLE
Unloading error - discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

### ISSUE THREAD

**Issue by gcruicks** [PilotsTradeNetwork/BoozeBot#122]
Jun  6 19:31:54 boozebot-1 python[21878]: An exception has occurred while executing command `wine_unload`:
Jun  6 19:31:54 boozebot-1 python[21878]: Traceback (most recent call last):
Jun  6 19:31:54 boozebot-1 python[21878]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord_slash/client.py", line 872, in invoke_command
Jun  6 19:31:54 boozebot-1 python[21878]:     await func.invoke(ctx, args)
Jun  6 19:31:54 boozebot-1 python[21878]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord_slash/model.py", line 288, in invoke
Jun  6 19:31:54 boozebot-1 python[21878]:     return await coro
Jun  6 19:31:54 boozebot-1 python[21878]:   File "/home/booze/ptn/BoozeBot/ptn/boozebot/commands/Unloading.py", line 273, in wine_carrier_unload
Jun  6 19:31:54 boozebot-1 python[21878]:     return await ctx.send(
Jun  6 19:31:54 boozebot-1 python[21878]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord_slash/context.py", line 206, in send
Jun  6 19:31:54 boozebot-1 python[21878]:     await self._http.post_initial_response(json_data, self.interaction_id, self.__token)
Jun  6 19:31:54 boozebot-1 python[21878]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord/http.py", line 250, in request
Jun  6 19:31:54 boozebot-1 python[21878]:     raise NotFound(r, data)
Jun  6 19:31:54 boozebot-1 python[21878]: discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

**Comment by gcruicks** [comment]
The error seemed to cause any logging to hang, even though the bot was running fine.

**Comment by gcruicks** [comment]
Not a repeatable issue
