### ISSUE TITLE
An invalid carrier ID causes the tally commands to fail

### ISSUE THREAD

**Issue by gcruicks** [PilotsTradeNetwork/BoozeBot#169]
Jul  3 07:02:44 boozebot-1 systemd[1]: fwupd-refresh.service: Succeeded.
Jul  3 07:02:44 boozebot-1 systemd[1]: Finished Refresh fwupd metadata and update motd.
Jul  3 07:57:03 boozebot-1 python[106045]: An exception has occurred while executing command `booze_tally`:
Jul  3 07:57:03 boozebot-1 python[106045]: Traceback (most recent call last):
Jul  3 07:57:03 boozebot-1 python[106045]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord_slash/client.py", line 872, in invoke_command
Jul  3 07:57:03 boozebot-1 python[106045]:     await func.invoke(ctx, args)
Jul  3 07:57:03 boozebot-1 python[106045]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord_slash/model.py", line 288, in invoke
Jul  3 07:57:03 boozebot-1 python[106045]:     return await coro
Jul  3 07:57:03 boozebot-1 python[106045]:   File "/home/booze/ptn/BoozeBot/ptn/boozebot/commands/DatabaseInteraction.py", line 839, in tally
Jul  3 07:57:03 boozebot-1 python[106045]:     await self.report_invalid_carriers(self._update_db())
Jul  3 07:57:03 boozebot-1 python[106045]:   File "/home/booze/ptn/BoozeBot/ptn/boozebot/commands/DatabaseInteraction.py", line 186, in _update_db
Jul  3 07:57:03 boozebot-1 python[106045]:     carrier = BoozeCarrier(record)
Jul  3 07:57:03 boozebot-1 python[106045]:   File "/home/booze/ptn/BoozeBot/ptn/boozebot/BoozeCarrier.py", line 29, in __init__
Jul  3 07:57:03 boozebot-1 python[106045]:     raise ValueError(f'Incompatible carrier ID found: {self.carrier_identifier} - {self.carrier_name}')
Jul  3 07:57:03 boozebot-1 python[106045]: ValueError: Incompatible carrier ID found: K0Z L0Q - TBL Admiral Janeway
Jul  3 07:57:16 boozebot-1 python[106045]: An exception has occurred while executing command `booze_tally`:
Jul  3 07:57:16 boozebot-1 python[106045]: Traceback (most recent call last):
Jul  3 07:57:16 boozebot-1 python[106045]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord_slash/client.py", line 872, in invoke_command
Jul  3 07:57:16 boozebot-1 python[106045]:     await func.invoke(ctx, args)
Jul  3 07:57:16 boozebot-1 python[106045]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord_slash/model.py", line 288, in invoke
Jul  3 07:57:16 boozebot-1 python[106045]:     return await coro
Jul  3 07:57:16 boozebot-1 python[106045]:   File "/home/booze/ptn/BoozeBot/ptn/boozebot/commands/DatabaseInteraction.py", line 839, in tally
Jul  3 07:57:16 boozebot-1 python[106045]:     await self.report_invalid_carriers(self._update_db())
Jul  3 07:57:16 boozebot-1 python[106045]:   File "/home/booze/ptn/BoozeBot/ptn/boozebot/commands/DatabaseInteraction.py", line 186, in _update_db
Jul  3 07:57:16 boozebot-1 python[106045]:     carrier = BoozeCarrier(record)
Jul  3 07:57:16 boozebot-1 python[106045]:   File "/home/booze/ptn/BoozeBot/ptn/boozebot/BoozeCarrier.py", line 29, in __init__
Jul  3 07:57:16 boozebot-1 python[106045]:     raise ValueError(f'Incompatible carrier ID found: {self.carrier_identifier} - {self.carrier_name}')
Jul  3 07:57:16 boozebot-1 python[106045]: ValueError: Incompatible carrier ID found: K0Z L0Q - TBL Admiral Janeway
Jul  3 07:58:03 boozebot-1 python[106045]: An exception has occurred while executing command `booze_tally`:
Jul  3 07:58:03 boozebot-1 python[106045]: Traceback (most recent call last):
Jul  3 07:58:03 boozebot-1 python[106045]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord_slash/client.py", line 872, in invoke_command
Jul  3 07:58:03 boozebot-1 python[106045]:     await func.invoke(ctx, args)
Jul  3 07:58:03 boozebot-1 python[106045]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord_slash/model.py", line 288, in invoke
Jul  3 07:58:03 boozebot-1 python[106045]:     return await coro
Jul  3 07:58:03 boozebot-1 python[106045]:   File "/home/booze/ptn/BoozeBot/ptn/boozebot/commands/DatabaseInteraction.py", line 839, in tally
Jul  3 07:58:03 boozebot-1 python[106045]:     await self.report_invalid_carriers(self._update_db())
Jul  3 07:58:03 boozebot-1 python[106045]:   File "/home/booze/ptn/BoozeBot/ptn/boozebot/commands/DatabaseInteraction.py", line 186, in _update_db
Jul  3 07:58:03 boozebot-1 python[106045]:     carrier = BoozeCarrier(record)
Jul  3 07:58:03 boozebot-1 python[106045]:   File "/home/booze/ptn/BoozeBot/ptn/boozebot/BoozeCarrier.py", line 29, in __init__
Jul  3 07:58:03 boozebot-1 python[106045]:     raise ValueError(f'Incompatible carrier ID found: {self.carrier_identifier} - {self.carrier_name}')
Jul  3 07:58:03 boozebot-1 python[106045]: ValueError: Incompatible carrier ID found: K0Z L0Q - TBL Admiral Janeway
Jul  3 07:58:16 boozebot-1 python[106045]: An exception has occurred while executing command `booze_tally`:
Jul  3 07:58:16 boozebot-1 python[106045]: Traceback (most recent call last):
Jul  3 07:58:16 boozebot-1 python[106045]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord_slash/client.py", line 872, in invoke_command
Jul  3 07:58:16 boozebot-1 python[106045]:     await func.invoke(ctx, args)
Jul  3 07:58:16 boozebot-1 python[106045]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord_slash/model.py", line 288, in invoke
Jul  3 07:58:16 boozebot-1 python[106045]:     return await coro
Jul  3 07:58:16 boozebot-1 python[106045]:   File "/home/booze/ptn/BoozeBot/ptn/boozebot/commands/DatabaseInteraction.py", line 839, in tally
Jul  3 07:58:16 boozebot-1 python[106045]:     await self.report_invalid_carriers(self._update_db())
Jul  3 07:58:16 boozebot-1 python[106045]:   File "/home/booze/ptn/BoozeBot/ptn/boozebot/commands/DatabaseInteraction.py", line 186, in _update_db
Jul  3 07:58:16 boozebot-1 python[106045]:     carrier = BoozeCarrier(record)
Jul  3 07:58:16 boozebot-1 python[106045]:   File "/home/booze/ptn/BoozeBot/ptn/boozebot/BoozeCarrier.py", line 29, in __init__
Jul  3 07:58:16 boozebot-1 python[106045]:     raise ValueError(f'Incompatible carrier ID found: {self.carrier_identifier} - {self.carrier_name}')
Jul  3 07:58:16 boozebot-1 python[106045]: ValueError: Incompatible carrier ID found: K0Z L0Q - TBL Admiral Janeway
Jul  3 07:58:45 boozebot-1 python[106045]: An exception has occurred while executing command `booze_tally_extra_stats`:
Jul  3 07:58:45 boozebot-1 python[106045]: Traceback (most recent call last):
Jul  3 07:58:45 boozebot-1 python[106045]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord_slash/client.py", line 872, in invoke_command
Jul  3 07:58:45 boozebot-1 python[106045]:     await func.invoke(ctx, args)
Jul  3 07:58:45 boozebot-1 python[106045]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord_slash/model.py", line 288, in invoke
Jul  3 07:58:45 boozebot-1 python[106045]:     return await coro
Jul  3 07:58:45 boozebot-1 python[106045]:   File "/home/booze/ptn/BoozeBot/ptn/boozebot/commands/DatabaseInteraction.py", line 1209, in extended_tally_stats
Jul  3 07:58:45 boozebot-1 python[106045]:     await self.report_invalid_carriers(self._update_db())
Jul  3 07:58:45 boozebot-1 python[106045]:   File "/home/booze/ptn/BoozeBot/ptn/boozebot/commands/DatabaseInteraction.py", line 186, in _update_db
Jul  3 07:58:45 boozebot-1 python[106045]:     carrier = BoozeCarrier(record)
Jul  3 07:58:45 boozebot-1 python[106045]:   File "/home/booze/ptn/BoozeBot/ptn/boozebot/BoozeCarrier.py", line 29, in __init__
Jul  3 07:58:45 boozebot-1 python[106045]:     raise ValueError(f'Incompatible carrier ID found: {self.carrier_identifier} - {self.carrier_name}')
Jul  3 07:58:45 boozebot-1 python[106045]: ValueError: Incompatible carrier ID found: K0Z L0Q - TBL Admiral Janeway

**Comment by gcruicks** [comment]
Also locks up the find commands. On a reboot this would also block the system and stop the bot as it will not populate.

Maybe we can consider populating, but ignoring the carrier and raising an error about it?

**Comment by gcruicks** [comment]
Or post a notification to the sommeliers that the ID is invalid
