### ISSUE TITLE
403 Fordbidden issues relating to pinning messages

### ISSUE THREAD

**Issue by gcruicks** [PilotsTradeNetwork/BoozeBot#198]
Jul 29 08:26:29 boozebot-1 python[189535]: Updating the database we have: 1 records found.
Jul 29 08:26:29 boozebot-1 python[189535]: ['123-321']
Jul 29 08:26:29 boozebot-1 python[189535]: [{'carrier_name': 'Testy McTestFace', 'carrier_id': '123-321', 'run_count': 1, 'wine_total': 1}]
Jul 29 08:26:29 boozebot-1 python[189535]: SELECT * FROM boozecarriers WHERE carrierid LIKE ('%123-321%')
Jul 29 08:26:30 boozebot-1 python[189535]: An exception has occurred while executing command `booze_tally`:
Jul 29 08:26:30 boozebot-1 python[189535]: Traceback (most recent call last):
Jul 29 08:26:30 boozebot-1 python[189535]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord_slash/client.py", line 872, in invoke_command
Jul 29 08:26:30 boozebot-1 python[189535]:     await func.invoke(ctx, args)
Jul 29 08:26:30 boozebot-1 python[189535]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord_slash/model.py", line 288, in invoke
Jul 29 08:26:30 boozebot-1 python[189535]:     return await coro
Jul 29 08:26:30 boozebot-1 python[189535]:   File "/home/booze/ptn/BoozeBot/ptn/boozebot/commands/DatabaseInteraction.py", line 913, in tally
Jul 29 08:26:30 boozebot-1 python[189535]:     channel = await bot.fetch_channel(pin['channel_id'])
Jul 29 08:26:30 boozebot-1 python[189535]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord/client.py", line 1459, in fetch_channel
Jul 29 08:26:30 boozebot-1 python[189535]:     data = await self.http.get_channel(channel_id)
Jul 29 08:26:30 boozebot-1 python[189535]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord/http.py", line 248, in request
Jul 29 08:26:30 boozebot-1 python[189535]:     raise Forbidden(r, data)
Jul 29 08:26:30 boozebot-1 python[189535]: discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
Jul 29 08:26:49 boozebot-1 python[189535]: An exception has occurred while executing command `booze_pin_message`:
Jul 29 08:26:49 boozebot-1 python[189535]: Traceback (most recent call last):
Jul 29 08:26:49 boozebot-1 python[189535]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord_slash/client.py", line 872, in invoke_command
Jul 29 08:26:49 boozebot-1 python[189535]:     await func.invoke(ctx, args)
Jul 29 08:26:49 boozebot-1 python[189535]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord_slash/model.py", line 288, in invoke
Jul 29 08:26:49 boozebot-1 python[189535]:     return await coro
Jul 29 08:26:49 boozebot-1 python[189535]:   File "/home/booze/ptn/BoozeBot/ptn/boozebot/commands/DatabaseInteraction.py", line 1040, in pin_message
Jul 29 08:26:49 boozebot-1 python[189535]:     message = await channel.fetch_message(int(message_id))
Jul 29 08:26:49 boozebot-1 python[189535]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord/abc.py", line 1132, in fetch_message
Jul 29 08:26:49 boozebot-1 python[189535]:     data = await self._state.http.get_message(channel.id, id)
Jul 29 08:26:49 boozebot-1 python[189535]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord/http.py", line 248, in request
Jul 29 08:26:49 boozebot-1 python[189535]:     raise Forbidden(r, data)
Jul 29 08:26:49 boozebot-1 python[189535]: discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
Jul 29 08:28:42 boozebot-1 python[189535]: An exception has occurred while executing command `booze_tally`:
Jul 29 08:28:42 boozebot-1 python[189535]: Traceback (most recent call last):
Jul 29 08:28:42 boozebot-1 python[189535]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord_slash/client.py", line 872, in invoke_command
Jul 29 08:28:42 boozebot-1 python[189535]:     await func.invoke(ctx, args)
Jul 29 08:28:42 boozebot-1 python[189535]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord_slash/model.py", line 288, in invoke
Jul 29 08:28:42 boozebot-1 python[189535]:     return await coro
Jul 29 08:28:42 boozebot-1 python[189535]:   File "/home/booze/ptn/BoozeBot/ptn/boozebot/commands/DatabaseInteraction.py", line 913, in tally
Jul 29 08:28:42 boozebot-1 python[189535]:     channel = await bot.fetch_channel(pin['channel_id'])
Jul 29 08:28:42 boozebot-1 python[189535]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord/client.py", line 1459, in fetch_channel
Jul 29 08:28:42 boozebot-1 python[189535]:     data = await self.http.get_channel(channel_id)
Jul 29 08:28:42 boozebot-1 python[189535]:   File "/home/booze/ptn/boozeBot3.9/lib/python3.9/site-packages/discord/http.py", line 248, in request
Jul 29 08:28:42 boozebot-1 python[189535]:     raise Forbidden(r, data)
Jul 29 08:28:42 boozebot-1 python[189535]: discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

**Comment by gcruicks** [comment]
Permission issue on the server side - resolved
