### ISSUE TITLE
No confirmation embed on /booze_channels_open

### ISSUE THREAD

**Issue by cimspin** [PilotsTradeNetwork/BoozeBot#383]
```2023-07-14T14:02:37.727843423Z User conshmea#0 requested BC channel opening in channel: 🦜steve-says-admin.
2023-07-14T14:02:41.222931899Z An exception has occurred while executing command `booze_channels_open`:
2023-07-14T14:02:41.223000059Z Traceback (most recent call last):
2023-07-14T14:02:41.223009252Z   File "/usr/local/lib/python3.10/site-packages/discord_slash/client.py", line 1353, in invoke_command
2023-07-14T14:02:41.223016522Z     await func.invoke(ctx, **args)
2023-07-14T14:02:41.223023195Z   File "/usr/local/lib/python3.10/site-packages/discord_slash/model.py", line 209, in invoke
2023-07-14T14:02:41.223030152Z     return await self.func(self.cog, *args, **kwargs)
2023-07-14T14:02:41.223036672Z   File "/usr/local/lib/python3.10/site-packages/ptn/boozebot/commands/Cleaner.py", line 62, in booze_channels_open
2023-07-14T14:02:41.223043659Z     await ctx.send(f"<@&{server_sommelier_role_id()}> Avast! We\'re ready to set sail!", embed=embed)
2023-07-14T14:02:41.223057219Z   File "/usr/local/lib/python3.10/site-packages/discord_slash/context.py", line 256, in send
2023-07-14T14:02:41.223064220Z     await self._http.post_initial_response(json_data, self.interaction_id, self._token)
2023-07-14T14:02:41.223071069Z   File "/usr/local/lib/python3.10/site-packages/discord/http.py", line 250, in request
2023-07-14T14:02:41.223077831Z     raise NotFound(r, data)
2023-07-14T14:02:41.223084407Z discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
```

Happened twice in a row, but why?

**Comment by cimspin** [comment]
We should reply before opening the channels then edit or delete the reply to make sure we respond within the mandated 3 seconds.
